name: pocketra
description: "Pocketra - Modern SME Cash Flow Dashboard"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^3.0.1
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  google_fonts: ^6.2.1
  dynamic_color: ^1.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.5.1
  fl_chart: ^0.70.2
  flutter_native_splash: ^2.4.0
  uuid: ^4.4.0
  flutter_gemini: ^3.0.0
  flutter_dotenv: ^6.0.0
  google_generative_ai: ^0.4.7
  share_plus: ^10.1.0
  path_provider: ^2.1.3
  file_picker: ^8.1.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

# App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web: false
  windows: false
  macos: false

# Splash Screen Configuration
flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android_12:
    image: assets/logo.png
    color: "@android:color/system_neutral1_10"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/icon/icon.png
