name: sme_cash_flow_dashboard
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^3.0.1
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  google_fonts: ^6.2.1
  dynamic_color: ^1.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.5.1
  fl_chart: ^0.70.2
  flutter_native_splash: ^2.4.0
  uuid: ^4.4.0
  flutter_gemini: ^3.0.0
  flutter_dotenv: ^6.0.0
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

# CORRECT PLACEMENT: Top-level (no indentation)
flutter_native_splash:
  color: "#ffffff" # Fallback color
  image: assets/logo.png

  android_12:
    image: assets/logo.png
    # Dynamic Material You background for Android 12+
    color: "@android:color/system_neutral1_10"

flutter:
  uses-material-design: true
  #assets:
   # - assets/logo.png
